services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  backend:
    build:
        context: ./backend
        dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
        context: ./frontend
        dockerfile: dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
