name: New app version

on:
  push:
    branches:
      - main

jobs:
  build:
    name: push images to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login
        id: docker-hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $username -p $password
      - name: build images
        id: build-docker-images
        run: |
          docker build app/backend -f app/backend/dockerfile -t backend-todo
          docker build app/frontend -f app/frontend/Dockerfile -t frontend-todo
      - name: tag images
        id: tag-docker-images
        run: |
          docker tag backend-todo ellocosdelpopos/backend-todo:latest
          docker tag frontend-todo ellocosdelpopos/frontend-todo:latest
      - name: push docker Images
        id: push-docker-images
        run: |
          docker push ellocosdelpopos/backend-todo:latest
          docker push ellocosdelpopos/frontend-todo:latest
